version: '3.8'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network
    depends_on:
      - python-app

  python-app:
    build:
      context: ./Python
      dockerfile: Dockerfile
    image: python-app
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge